In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.decomposition import PCA

In [2]:
salarydata = pd.read_csv("SalaryData_Train(1) (1).csv")
salarydata

age          workclass    education  educationno        maritalstatus  \
0       39          State-gov    Bachelors           13        Never-married   
1       50   Self-emp-not-inc    Bachelors           13   Married-civ-spouse   
2       38            Private      HS-grad            9             Divorced   
3       53            Private         11th            7   Married-civ-spouse   
4       28            Private    Bachelors           13   Married-civ-spouse   
...    ...                ...          ...          ...                  ...   
30156   27            Private   Assoc-acdm           12   Married-civ-spouse   
30157   40            Private      HS-grad            9   Married-civ-spouse   
30158   58            Private      HS-grad            9              Widowed   
30159   22            Private      HS-grad            9        Never-married   
30160   52       Self-emp-inc      HS-grad            9   Married-civ-spouse   

               occupation    relationship    race      sex  capitalgain  \
0            Adm-clerical   Not-in-family   White     Male         2174   
1         Exec-managerial         Husband   White     Male            0   
2       Handlers-cleaners   Not-in-family   White     Male            0   
3       Handlers-cleaners         Husband   Black     Male            0   
4          Prof-specialty            Wife   Black   Female            0   
...                   ...             ...     ...      ...          ...   
30156        Tech-support            Wife   White   Female            0   
30157   Machine-op-inspct         Husband   White     Male            0   
30158        Adm-clerical       Unmarried   White   Female            0   
30159        Adm-clerical       Own-child   White     Male            0   
30160     Exec-managerial            Wife   White   Female        15024   

       capitalloss  hoursperweek          native  Salary  
0                0            40   United-States   <=50K  
1                0            13   United-States   <=50K  
2                0            40   United-States   <=50K  
3                0            40   United-States   <=50K  
4                0            40            Cuba   <=50K  
...            ...           ...             ...     ...  
30156            0            38   United-States   <=50K  
30157            0            40   United-States    >50K  
30158            0            40   United-States   <=50K  
30159            0            20   United-States   <=50K  
30160            0            40   United-States    >50K  

[30161 rows x 14 columns]

In [3]:
salarydata.columns

Index(['age', 'workclass', 'education', 'educationno', 'maritalstatus',
       'occupation', 'relationship', 'race', 'sex', 'capitalgain',
       'capitalloss', 'hoursperweek', 'native', 'Salary'],
      dtype='object')

In [4]:
salarydata[salarydata.duplicated()]

age workclass      education  educationno        maritalstatus  \
326     33   Private      Bachelors           13   Married-civ-spouse   
364     27   Private      Bachelors           13        Never-married   
518     24   Private        HS-grad            9        Never-married   
525     24   Private        HS-grad            9        Never-married   
619     33   Private      Bachelors           13   Married-civ-spouse   
...    ...       ...            ...          ...                  ...   
30110   47   Private        HS-grad            9   Married-civ-spouse   
30118   20   Private        HS-grad            9        Never-married   
30132   22   Private   Some-college           10        Never-married   
30157   40   Private        HS-grad            9   Married-civ-spouse   
30159   22   Private        HS-grad            9        Never-married   

               occupation    relationship    race      sex  capitalgain  \
326       Exec-managerial         Husband   White     Male            0   
364          Craft-repair   Not-in-family   White     Male            0   
518     Handlers-cleaners       Unmarried   Black   Female            0   
525          Craft-repair       Own-child   White     Male            0   
619       Exec-managerial         Husband   White     Male            0   
...                   ...             ...     ...      ...          ...   
30110        Craft-repair         Husband   White     Male            0   
30118   Machine-op-inspct       Own-child   White     Male            0   
30132        Adm-clerical       Own-child   White     Male            0   
30157   Machine-op-inspct         Husband   White     Male            0   
30159        Adm-clerical       Own-child   White     Male            0   

       capitalloss  hoursperweek          native  Salary  
326              0            40   United-States    >50K  
364              0            50   United-States   <=50K  
518              0            40   United-States   <=50K  
525              0            40   United-States   <=50K  
619              0            40   United-States    >50K  
...            ...           ...             ...     ...  
30110            0            40   United-States   <=50K  
30118            0            40   United-States   <=50K  
30132            0            40   United-States   <=50K  
30157            0            40   United-States    >50K  
30159            0            20   United-States   <=50K  

[3258 rows x 14 columns]

In [5]:
salarydata1 = salarydata[~salarydata.duplicated()]
salarydata1

age          workclass      education  educationno  \
0       39          State-gov      Bachelors           13   
1       50   Self-emp-not-inc      Bachelors           13   
2       38            Private        HS-grad            9   
3       53            Private           11th            7   
4       28            Private      Bachelors           13   
...    ...                ...            ...          ...   
30154   53            Private        Masters           14   
30155   22            Private   Some-college           10   
30156   27            Private     Assoc-acdm           12   
30158   58            Private        HS-grad            9   
30160   52       Self-emp-inc        HS-grad            9   

             maritalstatus          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
30154   Married-civ-spouse     Exec-managerial         Husband   White   
30155        Never-married     Protective-serv   Not-in-family   White   
30156   Married-civ-spouse        Tech-support            Wife   White   
30158              Widowed        Adm-clerical       Unmarried   White   
30160   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capitalgain  capitalloss  hoursperweek          native  Salary  
0         Male         2174            0            40   United-States   <=50K  
1         Male            0            0            13   United-States   <=50K  
2         Male            0            0            40   United-States   <=50K  
3         Male            0            0            40   United-States   <=50K  
4       Female            0            0            40            Cuba   <=50K  
...        ...          ...          ...           ...             ...     ...  
30154     Male            0            0            40   United-States    >50K  
30155     Male            0            0            40   United-States   <=50K  
30156   Female            0            0            38   United-States   <=50K  
30158   Female            0            0            40   United-States   <=50K  
30160   Female        15024            0            40   United-States    >50K  

[26903 rows x 14 columns]

In [6]:
salarydata1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26903 entries, 0 to 30160
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            26903 non-null  int64 
 1   workclass      26903 non-null  object
 2   education      26903 non-null  object
 3   educationno    26903 non-null  int64 
 4   maritalstatus  26903 non-null  object
 5   occupation     26903 non-null  object
 6   relationship   26903 non-null  object
 7   race           26903 non-null  object
 8   sex            26903 non-null  object
 9   capitalgain    26903 non-null  int64 
 10  capitalloss    26903 non-null  int64 
 11  hoursperweek   26903 non-null  int64 
 12  native         26903 non-null  object
 13  Salary         26903 non-null  object
dtypes: int64(5), object(9)
memory usage: 3.1+ MB


In [7]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

In [12]:
salarydata1["Salary"]=le.fit_transform(salarydata1["Salary"])
salarydata1.head()

C:\Users\DELL\AppData\Local\Temp\ipykernel_4440\3167783412.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  salarydata1["Salary"]=le.fit_transform(salarydata1["Salary"])


age          workclass   education  educationno        maritalstatus  \
0   39          State-gov   Bachelors           13        Never-married   
1   50   Self-emp-not-inc   Bachelors           13   Married-civ-spouse   
2   38            Private     HS-grad            9             Divorced   
3   53            Private        11th            7   Married-civ-spouse   
4   28            Private   Bachelors           13   Married-civ-spouse   

           occupation    relationship    race      sex  capitalgain  \
0        Adm-clerical   Not-in-family   White     Male         2174   
1     Exec-managerial         Husband   White     Male            0   
2   Handlers-cleaners   Not-in-family   White     Male            0   
3   Handlers-cleaners         Husband   Black     Male            0   
4      Prof-specialty            Wife   Black   Female            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States       0  
1            0            13   United-States       0  
2            0            40   United-States       0  
3            0            40   United-States       0  
4            0            40            Cuba       0

In [13]:
salarydata2 = salarydata1.copy()
salarydata2.head()

age          workclass   education  educationno        maritalstatus  \
0   39          State-gov   Bachelors           13        Never-married   
1   50   Self-emp-not-inc   Bachelors           13   Married-civ-spouse   
2   38            Private     HS-grad            9             Divorced   
3   53            Private        11th            7   Married-civ-spouse   
4   28            Private   Bachelors           13   Married-civ-spouse   

           occupation    relationship    race      sex  capitalgain  \
0        Adm-clerical   Not-in-family   White     Male         2174   
1     Exec-managerial         Husband   White     Male            0   
2   Handlers-cleaners   Not-in-family   White     Male            0   
3   Handlers-cleaners         Husband   Black     Male            0   
4      Prof-specialty            Wife   Black   Female            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States       0  
1            0            13   United-States       0  
2            0            40   United-States       0  
3            0            40   United-States       0  
4            0            40            Cuba       0

In [14]:
salarydata1['workclass']=le.fit_transform(salarydata1['workclass'])
salarydata1['education']=le.fit_transform(salarydata1['education'])
salarydata1['maritalstatus']=le.fit_transform(salarydata1['maritalstatus'])
salarydata1['occupation']=le.fit_transform(salarydata1['occupation'])
salarydata1['relationship']=le.fit_transform(salarydata1['relationship'])
salarydata1['race']=le.fit_transform(salarydata1['race'])
salarydata1['sex']=le.fit_transform(salarydata1['sex'])
salarydata1['native']=le.fit_transform(salarydata1['native'])

C:\Users\DELL\AppData\Local\Temp\ipykernel_4440\1471887691.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  salarydata1['workclass']=le.fit_transform(salarydata1['workclass'])
C:\Users\DELL\AppData\Local\Temp\ipykernel_4440\1471887691.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  salarydata1['education']=le.fit_transform(salarydata1['education'])
C:\Users\DELL\AppData\Local\Temp\ipykernel_4440\1471887691.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFram

In [16]:
salarydata1.head()

age  workclass  education  educationno  maritalstatus  occupation  \
0   39          5          9           13              4           0   
1   50          4          9           13              2           3   
2   38          2         11            9              0           5   
3   53          2          1            7              2           5   
4   28          2          9           13              2           9   

   relationship  race  sex  capitalgain  capitalloss  hoursperweek  native  \
0             1     4    1         2174            0            40      37   
1             0     4    1            0            0            13      37   
2             1     4    1            0            0            40      37   
3             0     2    1            0            0            40      37   
4             5     2    0            0            0            40       4   

   Salary  
0       0  
1       0  
2       0  
3       0  
4       0

In [17]:
x=salarydata1.iloc[:,:13]
y=salarydata1.iloc[:,-1]

In [18]:
x

age  workclass  education  educationno  maritalstatus  occupation  \
0       39          5          9           13              4           0   
1       50          4          9           13              2           3   
2       38          2         11            9              0           5   
3       53          2          1            7              2           5   
4       28          2          9           13              2           9   
...    ...        ...        ...          ...            ...         ...   
30154   53          2         12           14              2           3   
30155   22          2         15           10              4          10   
30156   27          2          7           12              2          12   
30158   58          2         11            9              6           0   
30160   52          3         11            9              2           3   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  native  
0                 1     4    1         2174            0            40      37  
1                 0     4    1            0            0            13      37  
2                 1     4    1            0            0            40      37  
3                 0     2    1            0            0            40      37  
4                 5     2    0            0            0            40       4  
...             ...   ...  ...          ...          ...           ...     ...  
30154             0     4    1            0            0            40      37  
30155             1     4    1            0            0            40      37  
30156             5     4    0            0            0            38      37  
30158             4     4    0            0            0            40      37  
30160             5     4    0        15024            0            40      37  

[26903 rows x 13 columns]

In [19]:
y

0        0
1        0
2        0
3        0
4        0
        ..
30154    1
30155    0
30156    0
30158    0
30160    1
Name: Salary, Length: 26903, dtype: int32

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30,random_state=0)

In [22]:
x_train.shape

(18832, 13)

In [23]:
x_test.shape

(8071, 13)

In [24]:
from sklearn.preprocessing import StandardScaler

In [25]:
sc =StandardScaler()
x_train_std = sc.fit_transform(x_train)
x_test_std = sc.fit_transform(x_test)

In [26]:
x_train_std

array([[ 0.98277835, -0.21899829,  0.1893018 , ..., -0.23206223,
         0.55013951,  0.27925856],
       [ 0.07211662,  1.79919395,  0.1893018 , ..., -0.23206223,
         2.31821982,  0.27925856],
       [ 1.28633227, -0.21899829,  0.1893018 , ..., -0.23206223,
        -2.50381738,  0.27925856],
       ...,
       [-0.76265664,  2.80829007,  1.22720311, ..., -0.23206223,
        -0.09279878,  0.27925856],
       [-0.5349912 , -0.21899829,  0.1893018 , ..., -0.23206223,
        -0.49463521,  0.27925856],
       [-0.15554881, -0.21899829,  0.44877713, ..., -0.23206223,
         0.30903765,  0.27925856]])

In [27]:
x_test_std

array([[ 0.1477239 ,  0.77319757, -0.31268928, ..., -0.22962629,
        -0.09799812,  0.28968728],
       [-0.38197634,  2.75304452,  0.20156751, ..., -0.22962629,
        -0.09799812,  0.28968728],
       [ 0.67742414, -0.21672591, -1.59833125, ..., -0.22962629,
        -0.09799812, -4.72425953],
       ...,
       [ 0.90443852, -0.21672591,  0.20156751, ..., -0.22962629,
        -0.51054913,  0.28968728],
       [-0.45764781, -0.21672591, -1.34120285, ..., -0.22962629,
        -0.09799812, -1.74722861],
       [ 1.963839  ,  1.76312105,  0.97295269, ..., -0.22962629,
         1.55220593,  0.28968728]])

# SVM classification

In [30]:
svm = SVC (kernel = "rbf",random_state = 0,gamma=0.10,C=1)

In [31]:
svm.fit(x_train_std,y_train)

SVC(C=1, gamma=0.1, random_state=0)

In [32]:
y_pred = svm.predict(x_test)
y_pred

C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(


array([0, 0, 0, ..., 0, 0, 0])

In [33]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [34]:
acc = accuracy_score(y_test,y_pred)*100
print("Accuracy=",acc)
confusion_matrix(y_test,y_pred)

Accuracy= 74.71193160698797


array([[6030,    0],
       [2041,    0]], dtype=int64)

# changing some values of gamma and c,and cheak results

In [35]:
svm1 = SVC (kernel ="rbf",random_state =0,gamma="auto",C = 10)
svm1.fit(x_train_std,y_train)

SVC(C=10, gamma='auto', random_state=0)

In [36]:
y_pred_1 = svm1.predict(x_test)
y_pred_1

C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(


array([0, 0, 0, ..., 0, 0, 0])

In [37]:
acc_1 = accuracy_score(y_test,y_pred_1)*100
print("Accuracy=",acc_1)
confusion_matrix(y_test,y_pred_1)

Accuracy= 74.71193160698797


array([[6030,    0],
       [2041,    0]], dtype=int64)

In [38]:
svm2 = SVC (kernel ="sigmoid",random_state =0,gamma="auto",C = 10)
svm2.fit(x_train_std,y_train)

SVC(C=10, gamma='auto', kernel='sigmoid', random_state=0)

In [39]:
y_pred_2 = svm2.predict(x_test)
y_pred_2

C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(


array([1, 1, 1, ..., 1, 1, 0])

In [40]:
acc_2 = accuracy_score(y_test,y_pred_2)*100
print("Accuracy=",acc_2)
confusion_matrix(y_test,y_pred_2)

Accuracy= 26.812043117333662


array([[ 127, 5903],
       [   4, 2037]], dtype=int64)

# for testing data

In [41]:
salary_test = pd.read_csv("SalaryData_Test(1) (1).csv")
salary_test.shape

(15060, 14)

In [42]:
salary_test.head()

age   workclass      education  educationno        maritalstatus  \
0   25     Private           11th            7        Never-married   
1   38     Private        HS-grad            9   Married-civ-spouse   
2   28   Local-gov     Assoc-acdm           12   Married-civ-spouse   
3   44     Private   Some-college           10   Married-civ-spouse   
4   34     Private           10th            6        Never-married   

           occupation    relationship    race    sex  capitalgain  \
0   Machine-op-inspct       Own-child   Black   Male            0   
1     Farming-fishing         Husband   White   Male            0   
2     Protective-serv         Husband   White   Male            0   
3   Machine-op-inspct         Husband   Black   Male         7688   
4       Other-service   Not-in-family   White   Male            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            50   United-States   <=50K  
2            0            40   United-States    >50K  
3            0            40   United-States    >50K  
4            0            30   United-States   <=50K

In [43]:
salary_test[salary_test.duplicated()]

age workclass      education  educationno        maritalstatus  \
551     59   Private        HS-grad            9             Divorced   
601     32   Private        HS-grad            9   Married-civ-spouse   
681     40   Private        HS-grad            9   Married-civ-spouse   
799     24   Private      Bachelors           13        Never-married   
1044    44   Private    Prof-school           15   Married-civ-spouse   
...    ...       ...            ...          ...                  ...   
15043   51   Private        HS-grad            9   Married-civ-spouse   
15044   22   Private   Some-college           10        Never-married   
15049   32   Private        HS-grad            9   Married-civ-spouse   
15052   31   Private        HS-grad            9   Married-civ-spouse   
15053   25   Private        HS-grad            9        Never-married   

               occupation    relationship    race      sex  capitalgain  \
551         Other-service   Not-in-family   White   Female            0   
601                 Sales         Husband   White     Male            0   
681          Craft-repair         Husband   White     Male            0   
799        Prof-specialty   Not-in-family   White     Male            0   
1044       Prof-specialty         Husband   White     Male        99999   
...                   ...             ...     ...      ...          ...   
15043        Craft-repair         Husband   White     Male            0   
15044        Craft-repair       Own-child   White     Male            0   
15049   Handlers-cleaners         Husband   White     Male            0   
15052        Craft-repair         Husband   White     Male            0   
15053       Other-service       Own-child   White   Female            0   

       capitalloss  hoursperweek          native  Salary  
551              0            40   United-States   <=50K  
601              0            40   United-States   <=50K  
681              0            40   United-States   <=50K  
799              0            35   United-States   <=50K  
1044             0            60   United-States    >50K  
...            ...           ...             ...     ...  
15043            0            40   United-States   <=50K  
15044            0            40   United-States   <=50K  
15049            0            40   United-States   <=50K  
15052            0            40   United-States   <=50K  
15053            0            40   United-States   <=50K  

[930 rows x 14 columns]

In [48]:
salary_test1 = salary_test[~salary_test.duplicated()]
salary_test1 

age      workclass      education  educationno        maritalstatus  \
0       25        Private           11th            7        Never-married   
1       38        Private        HS-grad            9   Married-civ-spouse   
2       28      Local-gov     Assoc-acdm           12   Married-civ-spouse   
3       44        Private   Some-college           10   Married-civ-spouse   
4       34        Private           10th            6        Never-married   
...    ...            ...            ...          ...                  ...   
15055   33        Private      Bachelors           13        Never-married   
15056   39        Private      Bachelors           13             Divorced   
15057   38        Private      Bachelors           13   Married-civ-spouse   
15058   44        Private      Bachelors           13             Divorced   
15059   35   Self-emp-inc      Bachelors           13   Married-civ-spouse   

               occupation    relationship                 race      sex  \
0       Machine-op-inspct       Own-child                Black     Male   
1         Farming-fishing         Husband                White     Male   
2         Protective-serv         Husband                White     Male   
3       Machine-op-inspct         Husband                Black     Male   
4           Other-service   Not-in-family                White     Male   
...                   ...             ...                  ...      ...   
15055      Prof-specialty       Own-child                White     Male   
15056      Prof-specialty   Not-in-family                White   Female   
15057      Prof-specialty         Husband                White     Male   
15058        Adm-clerical       Own-child   Asian-Pac-Islander     Male   
15059     Exec-managerial         Husband                White     Male   

       capitalgain  capitalloss  hoursperweek          native  Salary  
0                0            0            40   United-States   <=50K  
1                0            0            50   United-States   <=50K  
2                0            0            40   United-States    >50K  
3             7688            0            40   United-States    >50K  
4                0            0            30   United-States   <=50K  
...            ...          ...           ...             ...     ...  
15055            0            0            40   United-States   <=50K  
15056            0            0            36   United-States   <=50K  
15057            0            0            50   United-States   <=50K  
15058         5455            0            40   United-States   <=50K  
15059            0            0            60   United-States    >50K  

[14130 rows x 14 columns]

In [49]:
salary_test1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14130 entries, 0 to 15059
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            14130 non-null  int64 
 1   workclass      14130 non-null  object
 2   education      14130 non-null  object
 3   educationno    14130 non-null  int64 
 4   maritalstatus  14130 non-null  object
 5   occupation     14130 non-null  object
 6   relationship   14130 non-null  object
 7   race           14130 non-null  object
 8   sex            14130 non-null  object
 9   capitalgain    14130 non-null  int64 
 10  capitalloss    14130 non-null  int64 
 11  hoursperweek   14130 non-null  int64 
 12  native         14130 non-null  object
 13  Salary         14130 non-null  object
dtypes: int64(5), object(9)
memory usage: 1.6+ MB


In [46]:
from sklearn import preprocessing
le_test = preprocessing.LabelEncoder()

In [50]:
salary_test1["Salary"]=le_test.fit_transform(salary_test_1["Salary"])
salary_test1.head()

C:\Users\DELL\AppData\Local\Temp\ipykernel_4440\284495240.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  salary_test1["Salary"]=le_test.fit_transform(salary_test_1["Salary"])


age   workclass      education  educationno        maritalstatus  \
0   25     Private           11th            7        Never-married   
1   38     Private        HS-grad            9   Married-civ-spouse   
2   28   Local-gov     Assoc-acdm           12   Married-civ-spouse   
3   44     Private   Some-college           10   Married-civ-spouse   
4   34     Private           10th            6        Never-married   

           occupation    relationship    race    sex  capitalgain  \
0   Machine-op-inspct       Own-child   Black   Male            0   
1     Farming-fishing         Husband   White   Male            0   
2     Protective-serv         Husband   White   Male            0   
3   Machine-op-inspct         Husband   Black   Male         7688   
4       Other-service   Not-in-family   White   Male            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States       0  
1            0            50   United-States       0  
2            0            40   United-States       1  
3            0            40   United-States       1  
4            0            30   United-States       0

In [51]:
salary_test1['workclass']=le.fit_transform(salary_test1['workclass'])
salary_test1['education']=le.fit_transform(salary_test1['education'])
salary_test1['maritalstatus']=le.fit_transform(salary_test1['maritalstatus'])
salary_test1['occupation']=le.fit_transform(salary_test1['occupation'])
salary_test1['relationship']=le.fit_transform(salary_test1['relationship'])
salary_test1['race']=le.fit_transform(salary_test1['race'])
salary_test1['sex']=le.fit_transform(salary_test1['sex'])
salary_test1['native']=le.fit_transform(salary_test1['native'])

C:\Users\DELL\AppData\Local\Temp\ipykernel_4440\1777549383.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  salary_test1['workclass']=le.fit_transform(salary_test1['workclass'])
C:\Users\DELL\AppData\Local\Temp\ipykernel_4440\1777549383.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  salary_test1['education']=le.fit_transform(salary_test1['education'])
C:\Users\DELL\AppData\Local\Temp\ipykernel_4440\1777549383.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a Data

In [52]:
salary_test1.head()

age  workclass  education  educationno  maritalstatus  occupation  \
0   25          2          1            7              4           6   
1   38          2         11            9              2           4   
2   28          1          7           12              2          10   
3   44          2         15           10              2           6   
4   34          2          0            6              4           7   

   relationship  race  sex  capitalgain  capitalloss  hoursperweek  native  \
0             3     2    1            0            0            40      37   
1             0     4    1            0            0            50      37   
2             0     4    1            0            0            40      37   
3             0     2    1         7688            0            40      37   
4             1     4    1            0            0            30      37   

   Salary  
0       0  
1       0  
2       1  
3       1  
4       0

In [53]:
x_1=salary_test1.iloc[:,:13]
y_1=salary_test1.iloc[:,-1]

In [54]:
x_1

age  workclass  education  educationno  maritalstatus  occupation  \
0       25          2          1            7              4           6   
1       38          2         11            9              2           4   
2       28          1          7           12              2          10   
3       44          2         15           10              2           6   
4       34          2          0            6              4           7   
...    ...        ...        ...          ...            ...         ...   
15055   33          2          9           13              4           9   
15056   39          2          9           13              0           9   
15057   38          2          9           13              2           9   
15058   44          2          9           13              0           0   
15059   35          3          9           13              2           3   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  native  
0                 3     2    1            0            0            40      37  
1                 0     4    1            0            0            50      37  
2                 0     4    1            0            0            40      37  
3                 0     2    1         7688            0            40      37  
4                 1     4    1            0            0            30      37  
...             ...   ...  ...          ...          ...           ...     ...  
15055             3     4    1            0            0            40      37  
15056             1     4    0            0            0            36      37  
15057             0     4    1            0            0            50      37  
15058             3     1    1         5455            0            40      37  
15059             0     4    1            0            0            60      37  

[14130 rows x 13 columns]

In [55]:
y_1

0        0
1        0
2        1
3        1
4        0
        ..
15055    0
15056    0
15057    0
15058    0
15059    1
Name: Salary, Length: 14130, dtype: int64

In [56]:
from sklearn.model_selection import train_test_split

In [57]:
x_train_1,x_test_1,y_train_1,y_test_1 = train_test_split(x_1,y_1,test_size=0.30,random_state=0)

In [58]:
x_train_1.shape

(9891, 13)

In [59]:
x_test_1.shape

(4239, 13)

In [60]:
from sklearn.preprocessing import StandardScaler

In [61]:
sc =StandardScaler()
x_train_1_std = sc.fit_transform(x_train_1)
x_test_1_std = sc.fit_transform(x_test_1)

In [62]:
x_train_1_std

array([[ 1.04045364,  0.77724298, -0.32023026, ...,  5.57703541,
         0.72911507,  0.26665689],
       [ 0.21764819, -0.23018859,  0.1972338 , ..., -0.22680389,
        -0.08647331,  0.26665689],
       [-0.60515726, -0.23018859, -0.32023026, ..., -0.22680389,
         0.32132088,  0.26665689],
       ...,
       [ 0.0680472 , -0.23018859, -0.83769433, ..., -0.22680389,
         0.32132088,  0.26665689],
       [ 0.51685017, -2.24505173, -0.83769433, ..., -0.22680389,
        -0.08647331, -4.29708252],
       [-1.35316221, -0.23018859,  1.23216193, ..., -0.22680389,
        -0.08647331,  0.26665689]])

# SVM classification

In [65]:
svm_test = SVC(kernel = "rbf",random_state=0,gamma=0.1,C = 1)
svm_test.fit(x_train_1_std,y_train_1)

SVC(C=1, gamma=0.1, random_state=0)

In [66]:
y_pred_test = svm_test.predict(x_test_1)
y_pred_test

C:\Users\DELL\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but SVC was fitted without feature names
  warnings.warn(


array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [67]:
acc_test = accuracy_score(y_test_1,y_pred_test)*100
print("Accuracy_test=",acc_test)
confusion_matrix(y_test_1,y_pred_test)

Accuracy_test= 74.85255956593537


array([[3173,    0],
       [1066,    0]], dtype=int64)

In [68]:
print("Accuracy of training data:- ", np.round(acc, 4),
     "\nAccuracy of testing data:- ", np.round(acc_test, 4))

Accuracy of training data:-  74.7119 
Accuracy of testing data:-  74.8526
